### ISSUE TITLE
Build Output Location

### ISSUE THREAD

**Issue by phillvancejr** [lichenscript/lichenscript#65]
Hello, I've toyed with lichenscript it a little, but I have no idea where the results of the build commands go. When using lsc build where does the executable go? The same when using --platform js, where does the js file go? I get no output in both situations.

**Comment by vincentdchan** [comment]
It's in the `.lichenscript` directory in the location you executed the command.
You can also use the argument `--build-dir` or `-D` to specify a directory.

**Comment by phillvancejr** [comment]
sorry, forgot to close this! It worked, thanks!
